### ISSUE TITLE
provide a basic reporter without dependencies

### ISSUE THREAD

**Issue by c-cube** [dbuenzli/logs#12]
I find it annoying that I have to write a reporter myself if I don't use Fmt (and all the fancy stuff associated). Is it possible to get a basic reporter packed in `Logs` itself?

**Comment by dbuenzli** [comment]
Could add that yes.

**Comment by c-cube** [comment]
Do you want me to implement one and make a PR?

**Comment by dbuenzli** [comment]
Thanks but don't bother it is basically going to be a C&P from https://github.com/dbuenzli/logs/blob/master/src/logs_fmt.ml#L24-L38 with `Fmt` substitued by `Format` and `Fmt.styled` removed. I'll do that later this evening.

**Comment by dbuenzli** [comment]
In fact rather than c&p it was rearranging code. So `Logs.format_reporter` behaves exactly like `Logs_fmt.reporter` except without colored headers and hence without the `Fmt` dependency. Tell me if that suits you.

**Comment by c-cube** [comment]
This looks very nice, thanks. It's good that you could avoid duplicating the code, and the API seems quite flexible.

**Comment by dbuenzli** [comment]
Had a glitch in the defaults, upgrade if pinned. I'll make a minor release in a few days.
