### ISSUE TITLE
No `dune` file?

### ISSUE THREAD

**Issue by francoisthire** [dbuenzli/logs#31]
`dune` seems to be the standard now. Probably this project should use it?

**Comment by dbuenzli** [comment]
The current build system is fine for me.

**Comment by francoisthire** [comment]
One issue I have is it for me difficult to vendor your library because of that. Maybe I am doing something wrong, but using `opam source` it is relatively easy to vendor libraries with `dune`. Maybe I am missing something, but at least for this point using `dune` seems better than the current solution.

**Comment by dbuenzli** [comment]
You can find `dune` overlays for some of my libs in this repository https://github.com/dune-universe/opam-overlays.

**Comment by francoisthire** [comment]
I did not that my project, thanks for the pointer.

Le dim. 8 nov. 2020 à 22:24, Daniel Bünzli <notifications@github.com> a
écrit :
