### ISSUE TITLE
Upstream a ppx

### ISSUE THREAD

**Issue by ulrikstrid** [dbuenzli/logs#32]
Hello! I created a small ppx to cut down on the boilerplate needed by hiding the fact that there a callback. It looks something like this:
`[%log info "Hello %s!" "World"]`
Do you want me to upstream it here or should I maintain and publish it on the side?

Thanks for this amazing library btw!

**Comment by dbuenzli** [comment]
No thanks ! I like to keep my program and libraries obvious and low maintenance.

**Comment by ulrikstrid** [comment]
I thought that might be the answer but didn't want to put it on the side if you actually wanted it.

Thanks for answering anyway

**Comment by dbuenzli** [comment]
No problem. Thanks for asking.
