### ISSUE TITLE
Print filename and line number before log

### ISSUE THREAD

**Issue by anchpop** [dbuenzli/logs#35]
Sometimes I waste a lot of time tracking down the file that's creating a log. Is there a way to set up a formatter to include the filename and line number that triggered a log?

**Comment by dbuenzli** [comment]
It's a bit unclear whether you are talking about creating a log or a log entry. I guess you could try to figure out some scheme using [these magic values](https://ocaml.org/api/Stdlib.html#1_Debugging). 

I  suggest you to ask/discuss that question on https://discuss.ocaml.org/ (you can log with your github account) where you will likely get more replies than here. 

(I'm closing this but feel free to continue the discussion or post what you came up with).

**Comment by dbuenzli** [comment]
[Post on discuss](https://discuss.ocaml.org/t/how-to-print-filenames-and-line-numbers-with-the-logs-library/8251).
