### ISSUE TITLE
Need a way to pass LDFLAG during build

### ISSUE THREAD

**Issue by satmandu** [dbuenzli/logs#41]
On `armv7l` I'm only able to build by using ld.bdf, not ld.gold.

How would I pass `LDFLAGS='-fuse-ld=ld.bfd'` to an opam install of `logs`? (I believe this is the traditional way of passing a linker request but maybe there's an ocaml way here?)

(Continuation of https://github.com/dbuenzli/logs/issues/39 )

**Comment by dbuenzli** [comment]
You should handle that at the OCaml compiler level.
