### ISSUE TITLE
Best way to mix Logs.xxx (fun ..) and Printf.printf ? 

### ISSUE THREAD

**Issue by tlh24** [dbuenzli/logs#50]
Hello, and thanks for the nice library ~

For my application, I'd like to output a progress status, eg: 

Printf.printf "\r done %d" counter; flush stdout; 

But, it seems that Logs 'grabs' stdout and or hides/buffers output (??).  Multi-threaded is enabled, though this does not seem to affect behavior.  

How to get the two printing methods to play well together?

**Comment by dbuenzli** [comment]
What happens depends on the [reporter](https://erratique.ch/software/logs/doc/Logs/index.html#reporters) you use. So you will likely need to provide more details. In any case as mentioned [here](https://github.com/dbuenzli/logs/blob/master/README.md#documentation). Questions should be asked on https://discuss.ocaml.org/ (where you can log with your gh account).
