### ISSUE TITLE
Nesting Tag.set

### ISSUE THREAD

**Issue by wokalski** [dbuenzli/logs#52]
In our structured logs we often end up with nested attributes. It seems to me like the natural structure to express it in Logs would be to extend `Tag.set` to be able to have set contain set children.

Do you have any thoughts on this, perhaps the API you'd like to see implemented?

**Comment by dbuenzli** [comment]
I don't understand the request. You can store arbitrary values in a `Tag.set`. That includes `Tag.set` values if you wish so. Isn't that sufficient for your purpose ?

**Comment by wokalski** [comment]
I believe it's not because I want the formatters to be aware of the nesting as well to be able to print nested sets differently depending on the reporter. for example in the case of json I would want nested sets to be represented by objects.

**Comment by dbuenzli** [comment]
Sorry I can't make sense of what you are saying. 

Your reporters can certainly lookup nested sets and represent them by objects, it's up to you. 

I think if we want this discussion to be productive you should rather come up with a concrete example of what you want to achieve and an explanation of why you can't do this with the current API. 

Then we can see if there's something we'd like to support or not here.

**Comment by dbuenzli** [comment]
I'm starting to think that perhaps you think that [this](https://erratique.ch/software/logs/doc/Logs/Tag/index.html#val-printer) is the only thing you can do in a reporter with a tag. But that's the only thing you can do for tags you *do not know*. 

For those that you know (i.e. the reporter is aware of the tag `'a Tag.def` value) you can [get back](https://erratique.ch/software/logs/doc/Logs/Tag/index.html#val-find) the concrete `'a` value and do whatever you wish with it.
